### ISSUE TITLE
Allow channel/link to come from a route name and parameters

### ISSUE THREAD

**Issue by jonathaningram** [eko/FeedBundle#11]
This means that you'd configure it something like this:

```yaml
eko_feed:
    feeds:
        post:
            link:
                type: route
                route_name: acme_blog_main_index
                route_params: {}
```

Of course it might vary, but the idea is that I don't have to hard-code a link URL or use a parameter, the latter of which I am currently doing:

```yaml
eko_feed:
    feeds:
        post:
            link:        'http://%acme_blog_hostname%/'
```
