### ISSUE TITLE
Flexible configuration.

### ISSUE THREAD

**Issue by jakon89** [eko/FeedBundle#39]
Hi
Is exists solution to avoid 'static' config, for example:

``` yaml
eko_feed:
    feeds:
        article:
            title:       'My articles/posts'
            description: 'Latests articles'
            link:        'http://vincent.composieux.fr'
            encoding:    'utf-8'
            author:      'Vincent Composieux' # Only required for Atom feeds
```

and do it dynamically for each request?

**Comment by jakenoble** [comment]
I am attempting to do this too, I am nearly there but I am now getting this

Catchable Fatal Error: Argument 1 passed to Acme\NameOfBundle\Service\UserRSSFeed::__construct() must implement interface Symfony\Component\Translation\TranslatorInterface, none given

Presumably at some point where I call this I need to pass in the correct object?

$feed = $this->get('eko_feed.feed.manager')->get("user_feed");

**Comment by eko** [comment]
Hi @jakenoble,

You need to pass the Symfony Translator to the formatter, this way:

```xml
<service id="acme.my_bundle.formatter.user_feed_rss" class="Acme\NameOfBundle\Service\UserRSSFeed">
    <tag name="eko_feed.formatter" format="custom"></tag>

    <argument type="service" id="translator" />
</service>
```

The `README.md` file is not up-to-date. Could you please send a PR to fix this? Otherwise I will fix it as soon as possible.

Thank you

**Comment by jakenoble** [comment]
Hi @eko, thanks for your time on this, great Bundle BTW.

I am nearly there with this now, thanks for the tip with the translator, my YML now looks like this
```
services:    
    acme.user_feed:
        class: Acme\NameOfBundle\Service\UserRSSFeed
        tags:
            - { name: eko_feed.formatter, format: user_feed }
        arguments: ["@translator"]
```
And this has fixed the previous error. But it now cannot find my custom user_feed and says;

> Specified feed 'user_feed' is not defined in your configuration.

If I then add this into my config, so it can "find" my custom config (note I do not think this is right?), then it loads but the `initialize` method in my custom Formatter is never executed.
```
user_feed:
    title:       'Custom Title'
    description: "Custom Desc"
    link:        'http://custom.com/feed'
    encoding:    'utf-8'
```
